### ISSUE TITLE
how to reproduce the result in offline environment , I dowload the sentence.model and checkpoint but, the sentencepiece.model can not be recognised by the t5~!!

### ISSUE THREAD

**Issue by flyingwaters** [bigscience-workshop/t-zero#21] opened 2022-03-09 07:55 UTC
hi @VictorSanh , i find Some problems when I reproduce your result. with t5==0.9.3,
I use gpus to train the model and the environ is offline ,so I get sentencepiece.model downloaded
and use this command
--gin_param="tsv_dataset_fn.vocabulary = SentencePieceVocabulary()"
--gin_param="get_sentencepiece_model_path = '/raid/yiptmp/huggingface-models/t5.1.1.lm100k.xxl'"
##################
but it has some problems ,as follow:
SyntaxError: malformed node or string: <_ast.Name object at 0x7f42f90404d0>
Failed to parse token 'SentencePieceVocabulary'
######################
I think T0 is nice, Can you fix this bug? and I think the t5 you used, maybe has be updated, can you provided the requirement with version number. I think I will help many researchers to reproduce it and develop this tech further~
Thanks your work !!!!
######################
the download story_cloze data should be saved at ~/.cache  ??? /i think there is no datapath in the command to add a task,

**Comment by VictorSanh** [comment] 2022-03-11 16:15
duplicate of #20. closing this.

**Closed by VictorSanh** 2022-03-11 16:15 UTC
